version: '3.7'

services:

  db:
    image: mariadb:10.6.4-focal
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
    ports:
      - 3306:3306
    volumes:
       - ./db-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  data:
  